version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t lambda/
  pre_build:
    commands:
      - echo Preparing Lambda function...
      - cp -r lambda/* /codebuild/output/lambda/
  build:
    commands:
      - echo Building Lambda function package...
      - zip -r lambda.zip /codebuild/output/lambda/
  post_build:
    commands:
      - echo Deploying Lambda function...
      - aws lambda update-function-code --function-name CICD_Lambda_Function --zip-file fileb://lambda.zip
      - echo Publishing new version...
      - VERSION=$(aws lambda publish-version --function-name CICD_Lambda_Function --query 'Version' --output text)
      - echo "New Lambda function version: $VERSION"
      - echo Promoting Lambda function version to alias...
      - aws lambda update-alias --function-name CICD_Lambda_Function --name stage --function-version $VERSION

artifacts:
  files:
    - lambda.zip
